# -*- coding: utf-8 -*-
"""10_loop_and_cond .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Loh8mj5e5g9QjP-omMX6igZhIlXxKYQ
"""

# Conditions and Loop
# 1. Write a program to check whether a given number is prime or not.
# 2. Write a program to print all the even numbers between 1 and 100 using a
# loop.
# 3. Write a program that reads a number and prints the factorial of that number
# using a while loop.
# 4. Write a program to print the multiplication table of a given number using a
# for loop.
# 5. Write a program to find the largest and smallest number in a list entered by
# the user.
# 6. Write a program that accepts 10 integers from the user and counts how many
# are positive, negative, and zero.
# 7. Write a program to generate the Fibonacci sequence up to n terms.
# 8. Write a program that reads a number and prints whether it is a palindrome or
# not.
# 9. Write a program that finds all numbers between 100 and 999 where the sum
# of the cubes of the digits equals the number itself (Armstrong numbers).

# 10.Write a menu-driven program to perform arithmetic operations (+, -, *, /)
# based on user choice using conditional statements.

#1
num=int(input("enter the number: "))
for i in range(2,num):
    if num%i==0:
        print("not prime number")
        break
    else:
        print("prime number")
        break

#2
print(*(i for i in range(100) if i%2==0))

#3
number=int(input("enter the number gor factorial: "))
fact=1
while number>1:
    fact*=number
    number-=1
print(fact)

# 4. Write a program to print the multiplication table of a given number using a
# for loop.
numb=int(input("enter the number gor factorial: "))
for i in range(1,11):
    print(f"{numb}*{i}={numb*i}")

# 5. Write a program to find the largest and smallest number in a list entered by
# the user.
lst = []
for _ in range(100):
    choice = input("Enter 'y' to proceed or any other key to stop: ")
    if choice != 'y':
        break
    num = int(input("Enter the number: "))
    lst.append(num)

print("largest number in Final list:", max(lst))
print("smallest number in Final list:", min(lst))

# 6. Write a program that accepts 10 integers from the user and counts how many
# are positive, negative, and zero.
import random
lst1=[random.randint(-100,100) for _ in range(10)]
dict_count={"zero":0,"negative":0,"positive":0}
for i in lst1:
    if i==0:
        dict_count["zero"]+=1
    elif i<0:
        dict_count["negative"]+=1
    else:
        dict_count["positive"]+=1
print("Generated list:", lst1)
print("Counts:", dict_count)

# 7. Write a program to generate the Fibonacci sequence up to n terms.
choic=int(input("enter the nth fibonacci upto: "))
fibo=[]
fibo.append(0)
fibo.append(1)
for i in range(2,choic+1):
    temp=fibo[i-2]+fibo[i-1]
    fibo.append(temp)
print(*(i for i in fibo))

# 8. Write a program that reads a number and prints whether it is a palindrome or
# not.
numbb = (input("Enter the number: "))
if numbb==numbb[::-1]:
    print(f"{int(numbb)} is a palindrome")

# 9. Write a program that finds all numbers between 100 and 999 where the sum
# of the cubes of the digits equals the number itself (Armstrong numbers).
num1=100
final_list=[]
while num1<1000:
    lstt=[int(d) for d in str(num1)]
    power=len(lstt)
    result=0
    for i in lstt:
        result+=i**power

    if result==num1:
        final_list.append(num1)
    num1+=1
print(final_list)

# 10.Write a menu-driven program to perform arithmetic operations (+, -, *, /)
# based on user choice using conditional statements.
print("\n==== Arithmetic Operations Menu =====")
print("1.Addition(+)")
print("2.subtraction(-)")
print("3.multiply(*)")
print("4.Division(/)")
print("5.exit")

while True:
    choice=int(input("enter the choice (1-5): "))
    if choice==5:
        break

    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == 1:
        print(f"Result: {num1} + {num2} = {num1 + num2}")
    elif choice == 2:
        print(f"Result: {num1} - {num2} = {num1 - num2}")
    elif choice == 3:
        print(f"Result: {num1} * {num2} = {num1 * num2}")
    elif choice == 4:
        if num2 != 0:
            print(f"Result: {num1} / {num2} = {num1 / num2}")
        else:
            print("Error: Division by zero!")
    else:
        print("Invalid choice. Please select a valid option.")



dict1 = {"math": 80, "science": 78, "social": 69, "english": 50}
dict2 = {"math": 85, "python": 78, "social": 67, "english": 76}
new_dict = {}

for key in dict1:
    new_dict[key] = dict1[key]

for key in dict2:
    if key in new_dict:
        new_dict[key] += dict2[key]
    else:
        new_dict[key] = dict2[key]

print(new_dict)